name: Backend CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Fpadminpostgre
          POSTGRES_DB: finanapp
        ports:
          - "5432:5432"

      redis:
        image: redis:latest
        ports:
          - "6379:6379"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Esperando o PostgreSQL..."
          until pg_isready -h localhost -p 5432; do
            sleep 1
          done
          echo "PostgreSQL pronto!"

      - name: Run database setup (setup_test.go)
        run: go test -v -run ^TestRunDatabaseSQL$ ./internal/db

      - name: Run all other tests
        run: go test -v ./internal/tests
